export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const REQUEST_NODES = 'REQUEST_NODES';
export const RECEIVE_NODES = 'RECEIVE_NODES';
export const REQUEST_FLOWS = 'REQUEST_FLOWS';
export const RECEIVE_FLOWS = 'RECEIVE_FLOWS';
export const RECEIVE_FLOWS_ERROR = 'RECEIVE_FLOWS_ERROR';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const TEST_ACTION = 'TEST_ACTION';
export const MOUSE_MOVE = 'MOUSE_MOVE';
export const MOUSE_UP = 'MOUSE_UP';
export const DELETE_PRESSED = 'DELETE_PRESSED';
export const DELETE_PORT = 'DELETE_PORT';

export const NODE_DROPPED = 'NODE_DROPPED';
export const NODE_SELECTED = 'NODE SELECTED'
export const NODE_TOUCH_START = 'NODE_TOUCH_START'; 
export const NODE_TOUCH_END = 'NODE_TOUCH_END';
export const NODE_DOUBLE_CLICKED = 'NODE_DOUBLE_CLICKED';
export const NODE_LOAD = 'NODE_LOAD';
export const NODE_MOUSE_DOWN = 'NODE_MOUSE_DOWN';
export const NODE_MOUSE_ENTER =  'NODE_MOUSE_ENTER';
export const NODE_MOUSE_LEAVE =  'NODE_MOUSE_LEAVE';

export const NODE_INIT_VALUES = 'NODE_INIT_VALUES';
export const NODE_UPDATE_VALUE = 'NODE_UPDATE_VALUE';
export const NODE_UPDATE_VALUE_KEY = 'NODE_UPDATE_VALUE_KEY';
export const NODE_INCREMENT_VALUE_KEY = 'NODE_INCREMENT_VALUE_KEY';

export const PORT_MOUSE_DOWN = 'PORT_MOUSE_DOWN';
export const PORT_MOUSE_UP = 'PORT_MOUSE_UP';
export const PORT_MOUSE_OVER = 'PORT_MOUSE_OVER';
export const PORT_MOUSE_OUT = 'PORT_MOUSE_OUT';

export const DIALOGUE_CANCEL = 'DIALOGUE_CANCEL';
export const DIALOGUE_OK = 'DIALOGUE_OK';

export const TOGGLE_DEPLOY_MENU='TOGGLE_DEPLOY_MENU';
export const TOGGLE_APPMANAGER = 'TOGGLE_APPMANAGER';
export const DEPLOY_CLICKED="DEPLOY_CLICKED";

export const SUBMITTING_FLOWS='SUBMITTING_FLOWS';
export const SUBMISSION_RESPONSE='SUBMISSION_RESPONSE';
export const SUBMISSION_ERROR='SUBMISSION_ERROR';

export const PUBLISHING_FLOWS='PUBLISHING_FLOWS';
export const PUBLISH_ERROR='PUBLISH_ERROR';
export const PUBLISH_RESPONSE='PUBLISH_RESPONSE';


export const REPO_NAME_CHANGED = 'REPO_NAME_CHANGED';
export const REPO_COMMIT_CHANGED ='REPO_COMMIT_CHANGED';
export const REPO_DESCRIPTION_CHANGED = 'REPO_DESCRIPTION_CHANGED';
export const REPO_SAVE_PRESSED = 'REPO_SAVE_PRESSED';
export const REPO_SAVING = 'REPO_SAVING';
export const REPO_REQUESTING_LIST = 'REPO_REQUESTING_LIST';
export const REPO_LIST_RETRIEVED = 'REPO_LIST_RETRIEVED';