export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const REQUEST_NODES = 'REQUEST_NODES';
export const RECEIVE_NODES = 'RECEIVE_NODES';
export const TEST_ACTION = 'TEST_ACTION';
export const REGISTER_TYPE = 'REGISTER_TYPE';


export const MOUSE_MOVE = 'MOUSE_MOVE';
export const MOUSE_UP = 'MOUSE_UP';



export const NODE_DROPPED = 'NODE_DROPPED';
export const NODE_SELECTED = 'NODE SELECTED'
export const NODE_TOUCH_START = 'NODE_TOUCH_START'; 
export const NODE_TOUCH_END = 'NODE_TOUCH_END';
export const NODE_DOUBLE_CLICKED = 'NODE_DOUBLE_CLICKED';
export const NODE_MOUSE_DOWN = 'NODE_MOUSE_DOWN';
export const NODE_MOUSE_ENTER =  'NODE_MOUSE_ENTER';
export const NODE_MOUSE_LEAVE =  'NODE_MOUSE_LEAVE';
export const NODE_CANCEL_CLICKED = 'NODE_CANCEL_CLICKED';


export const PORT_MOUSE_DOWN = 'PORT_MOUSE_DOWN';
export const PORT_MOUSE_UP = 'PORT_MOUSE_UP';
export const PORT_MOUSE_OVER = 'PORT_MOUSE_OVER';
export const PORT_MOUSE_OUT = 'PORT_MOUSE_OUT';